services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: energymeter_mqtt
    ports:
      - "8883:8883"
      - "1883:1883" # MQTT PORT without TLS (only for development)
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/acl.conf:/mosquitto/config/acl.conf
      # - mosquitto_data:/mosquitto/data
      # - mosquitto_log:/mosquitto/log
      - ./certs:/mosquitto/config/certs
    networks:
      - energymeter_net
    restart: always

  influxdb:
    image: influxdb:2.7
    container_name: energymeter_influx
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - energymeter_net
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: energymeter_postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - energymeter_net
    restart: always

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  influxdb_config:
  postgres_data:

networks:
  energymeter_net:
    driver: bridge
